version: '3.1'
services:
 nameapp:
   container_name: "appcontainer"
   depends_on:
     - mongo
   restart: always
   build: .
   ports:
     - "3000:4000"
   networks:
     - app
   volumes:
     - .:/usr/app
 mongo:
   image: mongo
   container_name: mongodb
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: "pass-root"
     MONGO_INITDB_DATABASE: "name-database"
   ports:
     - 27017:27017
   networks:
     - app
   volumes:
     - ~/mongo/data:/data/db
networks:
 app:
   driver: "bridge"